# coding: utf-8

"""
    Moosend API

    TODO: Add a description

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import moosend
from moosend.rest import ApiException
from moosend.models.subscribers150 import Subscribers150


class TestSubscribers150(unittest.TestCase):
    """ Subscribers150 unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSubscribers150(self):
        """
        Test Subscribers150
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = moosend.models.subscribers150.Subscribers150()
        pass


if __name__ == '__main__':
    unittest.main()
