# coding: utf-8

"""
    Moosend API

    TODO: Add a description

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import moosend
from moosend.rest import ApiException
from moosend.models.context140 import Context140


class TestContext140(unittest.TestCase):
    """ Context140 unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testContext140(self):
        """
        Test Context140
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = moosend.models.context140.Context140()
        pass


if __name__ == '__main__':
    unittest.main()
