# coding: utf-8

"""
    Moosend API

    TODO: Add a description

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import Moosend.Wrappers.PythonWrapper
from Moosend.Wrappers.PythonWrapper.rest import ApiException
from Moosend.Wrappers.PythonWrapper.models.getting_sender_details_response import GettingSenderDetailsResponse


class TestGettingSenderDetailsResponse(unittest.TestCase):
    """ GettingSenderDetailsResponse unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGettingSenderDetailsResponse(self):
        """
        Test GettingSenderDetailsResponse
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = Moosend.Wrappers.PythonWrapper.models.getting_sender_details_response.GettingSenderDetailsResponse()
        pass


if __name__ == '__main__':
    unittest.main()
