# coding: utf-8

"""
    Moosend API

    TODO: Add a description

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import Moosend.Wrappers.PythonWrapper
from Moosend.Wrappers.PythonWrapper.rest import ApiException
from Moosend.Wrappers.PythonWrapper.models.cloning_an_existing_campaign_response import CloningAnExistingCampaignResponse


class TestCloningAnExistingCampaignResponse(unittest.TestCase):
    """ CloningAnExistingCampaignResponse unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCloningAnExistingCampaignResponse(self):
        """
        Test CloningAnExistingCampaignResponse
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = Moosend.Wrappers.PythonWrapper.models.cloning_an_existing_campaign_response.CloningAnExistingCampaignResponse()
        pass


if __name__ == '__main__':
    unittest.main()
