# coding: utf-8

"""
    Moosend API

    TODO: Add a description

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import moosend
from moosend.rest import ApiException
from moosend.models.context import Context


class TestContext(unittest.TestCase):
    """ Context unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testContext(self):
        """
        Test Context
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = moosend.models.context.Context()
        pass


if __name__ == '__main__':
    unittest.main()
