# coding: utf-8

"""
    Moosend API

    TODO: Add a description

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import Moosend.Wrappers.PythonWrapper
from Moosend.Wrappers.PythonWrapper.rest import ApiException
from Moosend.Wrappers.PythonWrapper.models.mailing_list69 import MailingList69


class TestMailingList69(unittest.TestCase):
    """ MailingList69 unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMailingList69(self):
        """
        Test MailingList69
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = Moosend.Wrappers.PythonWrapper.models.mailing_list69.MailingList69()
        pass


if __name__ == '__main__':
    unittest.main()
