# coding: utf-8

"""
    Moosend API

    TODO: Add a description

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import moosend
from moosend.rest import ApiException
from moosend.models.get_campaign_statistics_with_paging_filtered_response import GetCampaignStatisticsWithPagingFilteredResponse


class TestGetCampaignStatisticsWithPagingFilteredResponse(unittest.TestCase):
    """ GetCampaignStatisticsWithPagingFilteredResponse unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetCampaignStatisticsWithPagingFilteredResponse(self):
        """
        Test GetCampaignStatisticsWithPagingFilteredResponse
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = moosend.models.get_campaign_statistics_with_paging_filtered_response.GetCampaignStatisticsWithPagingFilteredResponse()
        pass


if __name__ == '__main__':
    unittest.main()
