# coding: utf-8

"""
    Moosend API

    TODO: Add a description

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import Moosend.Wrappers.PythonWrapper
from Moosend.Wrappers.PythonWrapper.rest import ApiException
from Moosend.Wrappers.PythonWrapper.models.sending_a_campaign_response import SendingACampaignResponse


class TestSendingACampaignResponse(unittest.TestCase):
    """ SendingACampaignResponse unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSendingACampaignResponse(self):
        """
        Test SendingACampaignResponse
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = Moosend.Wrappers.PythonWrapper.models.sending_a_campaign_response.SendingACampaignResponse()
        pass


if __name__ == '__main__':
    unittest.main()
