# coding: utf-8

"""
    Moosend API

    TODO: Add a description

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import moosend
from moosend.rest import ApiException
from moosend.models.removing_a_subscriber_request import RemovingASubscriberRequest


class TestRemovingASubscriberRequest(unittest.TestCase):
    """ RemovingASubscriberRequest unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRemovingASubscriberRequest(self):
        """
        Test RemovingASubscriberRequest
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = moosend.models.removing_a_subscriber_request.RemovingASubscriberRequest()
        pass


if __name__ == '__main__':
    unittest.main()
