# coding: utf-8

"""
    Moosend API

    TODO: Add a description

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import Moosend.Wrappers.PythonWrapper
from Moosend.Wrappers.PythonWrapper.rest import ApiException
from Moosend.Wrappers.PythonWrapper.apis.segments_api import SegmentsApi


class TestSegmentsApi(unittest.TestCase):
    """ SegmentsApi unit test stubs """

    def setUp(self):
        self.api = Moosend.Wrappers.PythonWrapper.apis.segments_api.SegmentsApi()

    def tearDown(self):
        pass

    def test_adding_criteria_to_segments(self):
        """
        Test case for adding_criteria_to_segments

        Adding criteria to segments
        """
        pass

    def test_creating_a_new_segment(self):
        """
        Test case for creating_a_new_segment

        Creating a new segment
        """
        pass

    def test_deleting_a_segment(self):
        """
        Test case for deleting_a_segment

        Deleting A Segment
        """
        pass

    def test_getting_segment_details(self):
        """
        Test case for getting_segment_details

        Getting segment details
        """
        pass

    def test_getting_segment_subscribers(self):
        """
        Test case for getting_segment_subscribers

        Getting segment subscribers
        """
        pass

    def test_getting_segments(self):
        """
        Test case for getting_segments

        Getting segments
        """
        pass

    def test_updating_a_segment(self):
        """
        Test case for updating_a_segment

        Updating a segment
        """
        pass

    def test_updating_segment_criteria(self):
        """
        Test case for updating_segment_criteria

        Updating segment criteria
        """
        pass


if __name__ == '__main__':
    unittest.main()
