# coding: utf-8

"""
    Moosend API

    TODO: Add a description

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import moosend
from moosend.rest import ApiException
from moosend.models.deleting_a_segment_response import DeletingASegmentResponse


class TestDeletingASegmentResponse(unittest.TestCase):
    """ DeletingASegmentResponse unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDeletingASegmentResponse(self):
        """
        Test DeletingASegmentResponse
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = moosend.models.deleting_a_segment_response.DeletingASegmentResponse()
        pass


if __name__ == '__main__':
    unittest.main()
