# coding: utf-8

"""
    Moosend API

    TODO: Add a description

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import moosend
from moosend.rest import ApiException
from moosend.models.context110 import Context110


class TestContext110(unittest.TestCase):
    """ Context110 unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testContext110(self):
        """
        Test Context110
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = moosend.models.context110.Context110()
        pass


if __name__ == '__main__':
    unittest.main()
