# coding: utf-8

"""
    Moosend API

    TODO: Add a description

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import moosend
from moosend.rest import ApiException
from moosend.models.link_activity_response import LinkActivityResponse


class TestLinkActivityResponse(unittest.TestCase):
    """ LinkActivityResponse unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLinkActivityResponse(self):
        """
        Test LinkActivityResponse
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = moosend.models.link_activity_response.LinkActivityResponse()
        pass


if __name__ == '__main__':
    unittest.main()
