# coding: utf-8

"""
    Moosend API

    TODO: Add a description

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import Moosend.Wrappers.PythonWrapper
from Moosend.Wrappers.PythonWrapper.rest import ApiException
from Moosend.Wrappers.PythonWrapper.models.context145 import Context145


class TestContext145(unittest.TestCase):
    """ Context145 unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testContext145(self):
        """
        Test Context145
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = Moosend.Wrappers.PythonWrapper.models.context145.Context145()
        pass


if __name__ == '__main__':
    unittest.main()
