# coding: utf-8

"""
    Moosend API

    TODO: Add a description

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import moosend
from moosend.rest import ApiException
from moosend.models.context17 import Context17


class TestContext17(unittest.TestCase):
    """ Context17 unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testContext17(self):
        """
        Test Context17
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = moosend.models.context17.Context17()
        pass


if __name__ == '__main__':
    unittest.main()
