# coding: utf-8

"""
    Moosend API

    TODO: Add a description

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import moosend
from moosend.rest import ApiException
from moosend.models.format import Format


class TestFormat(unittest.TestCase):
    """ Format unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFormat(self):
        """
        Test Format
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = moosend.models.format.Format()
        pass


if __name__ == '__main__':
    unittest.main()
