# coding: utf-8

"""
    Moosend API

    TODO: Add a description

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import moosend
from moosend.rest import ApiException
from moosend.apis.mailing_lists_api import MailingListsApi


class TestMailingListsApi(unittest.TestCase):
    """ MailingListsApi unit test stubs """

    def setUp(self):
        self.api = moosend.apis.mailing_lists_api.MailingListsApi()

    def tearDown(self):
        pass

    def test_creating_a_custom_field(self):
        """
        Test case for creating_a_custom_field

        Creating a custom field
        """
        pass

    def test_creating_a_mailing_list(self):
        """
        Test case for creating_a_mailing_list

        Creating a mailing list
        """
        pass

    def test_deleting_a_mailing_list(self):
        """
        Test case for deleting_a_mailing_list

        Deleting a mailing list
        """
        pass

    def test_getting_all_active_mailing_lists(self):
        """
        Test case for getting_all_active_mailing_lists

        Getting all active mailing lists
        """
        pass

    def test_getting_all_active_mailing_lists_with_paging(self):
        """
        Test case for getting_all_active_mailing_lists_with_paging

        Getting all active mailing lists with paging
        """
        pass

    def test_getting_mailing_list_details(self):
        """
        Test case for getting_mailing_list_details

        Getting mailing list details
        """
        pass

    def test_removing_a_custom_field(self):
        """
        Test case for removing_a_custom_field

        Removing a custom field
        """
        pass

    def test_updating_a_custom_field(self):
        """
        Test case for updating_a_custom_field

        Updating a custom field
        """
        pass

    def test_updating_a_mailing_list(self):
        """
        Test case for updating_a_mailing_list

        Updating a mailing list
        """
        pass


if __name__ == '__main__':
    unittest.main()
